services:
  ai_service:
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - rabbitmq
  sms_service:
    build:
      context: ./sms_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"